In [1]:
import numpy as np

In [25]:
#Exercise1
#Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. 
arr=np.arange(1,11)
print(arr)
arr1=arr.reshape(2,5)
print(arr1)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [27]:
#Exercise2
#Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.
arr=np.arange(1,21)
print(arr)
arr1=arr[5:15]
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11 12 13 14 15]


In [37]:
#Exercise3
#Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. 
#Then, add a new item to the series with the key 'pears' and the value 4
x1=pd.Series({"apples":3,"Bananas":2,"Oranges":1})
x1["Pears"]=4
print(x1)



apples     3
Bananas    2
Oranges    1
Pears      4
dtype: int64


In [144]:
#Exercise4
#Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.
data = ({
    "name":["John","Anna","Peter","Linda","Tom","Jessica","Michael","Sophia","William","Emily"],
    "age": np.random.randint(20,60,10),
    "Gender":["Male","Female","Male","Female","Male","Female","Male","Female","Male","Female"]
})
df=pd.DataFrame(data)
print(df)


      name  age  Gender
0     John   57    Male
1     Anna   37  Female
2    Peter   59    Male
3    Linda   36  Female
4      Tom   33    Male
5  Jessica   35  Female
6  Michael   56    Male
7   Sophia   47  Female
8  William   37    Male
9    Emily   52  Female


In [81]:
#Exercise5
#Add a new column to the data frame created in question 1, called occupation.
#The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe
df["Occupation"] = ["Programmer","Manager","Analyst","Programmer","Manager","Analyst","Programmer","Manager","Analyst","Programmer"]
print(df)


      name  age  Gender  Occupation
0     John   56    Male  Programmer
1     Anna   57  Female     Manager
2    Peter   39    Male     Analyst
3    Linda   21  Female  Programmer
4      Tom   30    Male     Manager
5  Jessica   43  Female     Analyst
6  Michael   23    Male  Programmer
7   Sophia   49  Female     Manager
8  William   20    Male     Analyst
9    Emily   56  Female  Programmer


In [67]:
#Exercise6
#Select the rows of the dataframe where the age is greater than or equal to 30. 
df1=df.loc[df["age"]>=30]
df1


name  age  Gender  Occupation
0     John   58    Male  Programmer
1     Anna   42  Female     Manager
2    Peter   39    Male     Analyst
6  Michael   46    Male  Programmer
7   Sophia   42  Female     Manager
8  William   56    Male     Analyst
9    Emily   34  Female  Programmer

In [152]:
#Exercise7
# Convert this dataframe to a csv file and read that csv file, finally display the contents.
df.to_csv("data.csv")
Data = pd.read_csv("data.csv")
print(Data)

   Unnamed: 0     name  age  Gender
0           0     John   57    Male
1           1     Anna   37  Female
2           2    Peter   59    Male
3           3    Linda   36  Female
4           4      Tom   33    Male
5           5  Jessica   35  Female
6           6  Michael   56    Male
7           7   Sophia   47  Female
8           8  William   37    Male
9           9    Emily   52  Female
